export const loginUrl = "/customer/account/login";
export const registerUrl = "/customer/account/create";
export const forgotPasswordUrl = "/customer/account/forgotpassword";
export const forgotPasswordConfirmUrl = "/customer/account/forgotpassword/confirm-email";
export const checkOutUrl = "/checkout";
export const shopCartUrl = "/shop-cart";
export const shopUrl = "/shop";
export const contactUsUrl = "/contact-us";
export const userAccountOrderUrl = "/user-account/orders";
export const userAccountUrl = "/user-account/account";
export const userAddressUrl = "/user-account/address";
export const userShopingCartUrl = "/user-account/shopingCart";
export const userFavouriteUrl = "/user-account/favourite";
export const userSettingUrl = "/user-account/setting";
export const userPaymentUrl = "/user-account/payment";
export const userInvoiceUrl = "/user-account/invoice";
export const passwordResetSuccessUrl="/customer/account/forgotpassword/reset-successful"
export const homeUrl="/"
export const guestFormUrl="/sales/guest/form"
export const viewOrderUrl="/viewOrder"
export const termsUrl="/terms"
export const ourStoreUrl="/our-store"
export const helpCenterUrl="/help-center"
export const downloadableProductUrl="/user-account/downloadableProducts";